### ISSUE TITLE
SyntaxError: Unexpected token { in JSON at position 44

### ISSUE THREAD

**Issue by gehrausundspiel** [cahek2202/ioBroker.yeelight#5]
Hallo bei mir kommt folgende Fehlermeldung:
SyntaxError: Unexpected token { in JSON at position 44 oder
SyntaxError: Unexpected token { in JSON at position 27

und als Warnung:
Errror verifying active_bright command

Woran kann dies liegen?

############################################

Hello I get we following error:
SyntaxError: Unexpected token { in JSON at position 44 or
SyntaxError: Unexpected token { in JSON at position 27

and this warning:
Errror verifying active_bright command

What is this?

**Comment by Night2k5** [comment]
I am getting the same Error when trying to set the state of a normal non-RGB yeelight lamp.

**Comment by Snatch2001** [comment]
Bei mir der gleiche Fehler. Gibt es dazu eine Lösung?

**Comment by gehrausundspiel** [comment]
Its works finally with 1.0.1.
